### ISSUE TITLE
Checkbox not displaying its state during bucket creation

### ISSUE THREAD

**Issue by sQmmy** [KayatoSan/Budget5S#1]
It seems that on my setup (chrome version 125.0.6422.113 (64 bits))

During a bucket creation, the checkboxes are not displaying their real state (checked) :

before : 
![image](https://github.com/KayatoSan/Budget5S/assets/26865243/7e89e5cd-d024-4ee1-a472-7992ae52f658)

after clicking : 
![image](https://github.com/KayatoSan/Budget5S/assets/26865243/898d941e-d614-4bf2-adcf-a6797359dce7)

**Comment by KayatoSan** [comment]
[https://github.com/KayatoSan/Budget5S/commit/eaa4329b4782770c8cff315067d740176cd902db](https://github.com/KayatoSan/Budget5S/commit/eaa4329b4782770c8cff315067d740176cd902db)

Fixed, build and launch again the container 😉
