### ISSUE TITLE
Main page disappears after 3 seconds

### ISSUE THREAD

**Issue by lukasitaly** [KayatoSan/Budget5S#3]
So I just set up Budget5S. I went to port 7234 and the main page disappeared after 3 seconds. Just a white, blank page. If I quickly load any other page like Accounts or Buckets it works, but as soon as I switch back to the main page it disappears again. I didn't change anything except the ports in the compose file. Here's my compose:

```docker 
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "7234:80"
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7235:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
```

Here's a gif to show what I mean:
![budget5s](https://github.com/user-attachments/assets/77ba9ab0-64a7-41de-adf1-1a828a210a07)
I first load different pages like Accounts or Buckets and then switch to the main page, you can see it disappears after a few seconds

**Comment by KayatoSan** [comment]
Hi @lukasitaly !

If you want to put 7235 in your server service, you must also change the .env of vitejs : 

https://github.com/KayatoSan/Budget5S/blob/main/client/.env

If you haven't done so, your front end will still try 3000

I can't try it right now, but I think that's the problem.

**Comment by dariuszszyc** [comment]
I have the same issue, even if I don't change the ports of the server (except port 80 of client which I changed to a different one).

![image](https://github.com/user-attachments/assets/1b2e18ce-e3a6-4621-9ee1-912c13389221)

**Comment by lukasitaly** [comment]
Yea I forgot to comment sorry, I tested this yesterday. Didn't change, the main page still disappears

**Comment by dariuszszyc** [comment]
I mean - it's obvious why it happens.
Budget5S is on remote host (192.168.1.4 in my case) yet the request is send to localhost - which is my own laptop.

But even if I change .env

![image](https://github.com/user-attachments/assets/2d9a47be-1199-4047-afe0-1aa66f32ca20)

The requests are still sent to "localhost"

**Comment by dariuszszyc** [comment]
Ok, fixed it. So basically you have to update the .env in client folder.
Then you have to do again the "docker-compose build" and "docker-compose up -d"

For sure this needs to be changed so that it respects environment variables from docker-compose.yml instead of the .env which is built into docker image.

**Comment by zeusraman** [comment]
i am having similar issue on docker .. havent changed any ports yet ..but the screen blinks on reload for a second then nothing .. have tried different browsers .. 
Would love to get this and see if i can use it ..cheers

**Comment by KayatoSan** [comment]
Hi everybody !

Thank you for your feedback, indeed, I know that the configuration of the container is to review the environment variables, sorry, I had done a local and I did not really try to change ports or host and I published, I will test and fix that this weekend or early this week

I'll make sure the env variables are linked to the container

**Comment by KayatoSan** [comment]
> Yea I forgot to comment sorry, I tested this yesterday. Didn't change, the main page still disappears

I tested it today, with your docker-compose, on docker, it works, the little trick is as @dariuszszyc says you have to change the port pointing to the backend in the .env of vitejs **before** building the image, because the 'client' service will do a npm run build and replace the port in the code directly.

> i am having similar issue on docker .. havent changed any ports yet ..but the screen blinks on reload for a second then nothing .. have tried different browsers .. Would love to get this and see if i can use it ..cheers

Don't you have an error in the console? Did you run the container as is without changing anything? Aren't there any other conflicting services?
